### ISSUE TITLE
Authentication認証の調査・作業ログ

### ISSUE THREAD

**Issue by aoki2002** [aoki2002/sns_app#5]
## 概要
SNSアプリの新規登録・ログイン機能で使用しているFirebase Authenticationの認証に関する調査・作業ログ。

## 現状
以下のエラーが出力されている。
```
Initial task failed for action RecaptchaAction(action=signUpPassword)with exception - The email address is badly formatted.
```
メールアドレスの形式が間違っているという主旨のエラーだが、SignUpViewの登録ボタンをクリックした際にSignUpViewModelのModelを呼び出す関数が呼び出されていないこともLogで確認できた。

Authenticationに適当なメールアドレスの形式の調査を行うとともに、SignUpViewModelの関数が呼び出されていない原因を調査する。そしてAuthentication認証による新規登録・ログイン機能の実装を行う。

**Comment by aoki2002** [comment]
## Authenticationにおけるメールアドレス形式に関する調査・検証

### 調査
1. メールアドレスを入力するEditTextのinputType属性が"text"に設定していることが原因であると仮定した。
記事 : https://qiita.com/joji/items/41cc6cbedb7b84b632df

2. メールアドレスを格納する変数の型がAuthenticationのメールアドレスの形式と異なっていることが原因であると仮定した。
記事 : https://stackoverflow.com/questions/39664910/the-email-address-is-badly-formatted-firebase

3. SignUpViewのXML内の登録ボタンのクリックイベントが検知されていないことについて、SignUpViewModel・XML間のDataBindingの設定の確認を行った。
記事 : https://qiita.com/pikohan/items/4a59fcb625727790984e

**Comment by aoki2002** [comment]
### 検証
1.  SignUpViewのXML内のメールアドレスを入力するEditTextのinputType属性を"text"から"textEmailAddress"に変更する。

2. 文字列の先頭・末尾の空白を削除するtrimメソッドをメールアドレスを格納する変数に使用する。

**Comment by aoki2002** [comment]
### 検証結果
1. 以下のエラー内容は変わらず出力される。
```
The email address is badly formatted.
```

2. 以下のエラー内容は変わらず出力される。
```
The email address is badly formatted.
```

**Comment by yota-hara** [comment]
> Authenticationに適当なメールアドレスの形式

については`xxx@xx.xx`でいけた気がしますね。

> メールアドレスの形式が間違っているという主旨のエラーだが、SignUpViewの登録ボタンをクリックした際にSignUpViewModelのModelを呼び出す関数が呼び出されていないこともLogで確認できた。

Modelを呼び出していなければFirebaseとの通信疎通も行われていないかと思いますがいかがでしょうか？

> The email address is badly formatted.

このエラーログはAndroidStudioのものですかね？Firebaseと通信が行われていないのであればFirebaseのレスポンスではないのかなと思いますが、どうでしょうか？

**Comment by yota-hara** [comment]
@aoki2002 さん
* https://github.com/aoki2002/sns_app/issues/5#issuecomment-1641412203

**Comment by yota-hara** [comment]
@aoki2002 さん

どの仮説に対してどの時点でどんな検証を行って、どこまで可能性潰せているのかわかりづらいです。
ログの残し方としては、仮説を並列に並べるのでなく、一つ一つ検証して、結果から次の仮説を立ててまた検証するようにしてください。

# 仮説１
:
## 検証方法
:
## 検証結果
:
***

# （仮説1の検証結果を踏まえた）仮説２
:
## 検証方法
:
## 検証結果
:

**Comment by yota-hara** [comment]
> Authenticationに適当なメールアドレスの形式

については実際に入力で受け取ってmodelに渡している値をログ出力などで確認して下さい。

**Comment by aoki2002** [comment]
> > Authenticationに適当なメールアドレスの形式
> 
> については`xxx@xx.xx`でいけた気がしますね。
> 
> > メールアドレスの形式が間違っているという主旨のエラーだが、SignUpViewの登録ボタンをクリックした際にSignUpViewModelのModelを呼び出す関数が呼び出されていないこともLogで確認できた。
> 
> Modelを呼び出していなければFirebaseとの通信疎通も行われていないかと思いますがいかがでしょうか？
> 
> > The email address is badly formatted.
> 
> このエラーログはAndroidStudioのものですかね？Firebaseと通信が行われていないのであればFirebaseのレスポンスではないのかなと思いますが、どうでしょうか？

**Comment by aoki2002** [comment]
> > Authenticationに適当なメールアドレスの形式
> 
> については`xxx@xx.xx`でいけた気がしますね。
> 
> > メールアドレスの形式が間違っているという主旨のエラーだが、SignUpViewの登録ボタンをクリックした際にSignUpViewModelのModelを呼び出す関数が呼び出されていないこともLogで確認できた。
> 
> Modelを呼び出していなければFirebaseとの通信疎通も行われていないかと思いますがいかがでしょうか？
> 
> > The email address is badly formatted.
> 
> このエラーログはAndroidStudioのものですかね？Firebaseと通信が行われていないのであればFirebaseのレスポンスではないのかなと思いますが、どうでしょうか？

フィードバックありがとうございます。

・メールアドレスの形式は`xxx@xx.xx`で入力しているのですが同様のエラーが出力されたままです。

・Firebaseとの通信疎通は行われていないと思われます。XML内の登録ボタンのonClick属性でViewModelの特定の関数を呼び出すようにしているのですが現状動作していません。

・以下が現在出力されているエラーの全文であるため、Firebase関連のエラーだと思います。
```
Initial task failed for action RecaptchaAction(action=signUpPassword)with exception - The email address is badly formatted.
```
